services:
  - type: worker
    name: cdv-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cdv.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
